Fix recv() errors when closed during handshake (#704)
[closes #244]

Previously, if the application tried to close the connection before the
handshake completed, uvicorn would log:

    TypeError: An asyncio.Future, a coroutine or an awaitable is required.

These TypeErrors happen in tests/protocols/test_websocket.py. pytest is
hiding them. In my initial pull request, I added `caplog` to
`test_websocket.py` to expose the bug:

    def test_close_connection(protocol_cls, caplog):
        caplog.set_level(logging.ERROR)
        # ...
        assert not [r.message for r in caplog.records]

... but this caused unrelated errors on Windows; so @florimondmanca
suggests leaving the test suite alone, in
https://github.com/encode/uvicorn/pull/704#issuecomment-740926960